const SupplierActionTypes = {
    ADD_SUPPLIER: 'ADD_SUPPLIER',
    FETCH_SUPPLIERS: 'FETCH_SUPPLIERS',
    UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
    DELETE_SUPPLIER: 'DELETE_SUPPLIER'
}

export default SupplierActionTypes;