const EquipmentGroupActionTypes = {
    ADD_EQUIPMENT_GROUP: 'ADD_EQUIPMENT_GROUP', 
    CLEAN_EQUIPMENT_GROUP: 'CLEAN_EQUIPMENT_GROUP',
    DELETE_EQUIPMENT_GROUP: 'DELETE_EQUIPMENT_GROUP',
    FETCH_EQUIPMENT_GROUP: 'FETCH_EQUIPMENT_GROUP'
}

export default EquipmentGroupActionTypes;